export const ADD_BURGER_INGREDIENT ='ADD_BURGER_INGREDIENT'
export const REMOVE_BURGER_INGREDIENT ='REMOVE_BURGER_INGREDIENT'   
export const SET_BURGER_INGREDIENT = 'SET_BURGER_INGREDIENT'
export const POST_ORDER_DETAILS_SUCCESS = 'POST_ORDER_DETAILS_SUCCESS' 